### Sign in admin
POST http://localhost:4000/api/signin
Content-Type: application/json

{
    "username": "admin@admin.com",
    "password": "pd$rCh8,"
}

### Get global weekdays for rooms
GET http://localhost:4000/api/settings/global/weekdays

### Get one global weekday for rooms
GET http://localhost:4000/api/settings/global/weekdays/6

### Change all global weekdays for rooms
PUT http://localhost:4000/api/settings/global/weekdays
Content-Type: application/json

{
    "availability": true,
    "time_begin": "10:00",
    "time_end": "11:00"
}

### Restore global weekdays for rooms
DELETE http://localhost:4000/api/settings/global/weekdays

### Restore one global weekday for rooms
DELETE http://localhost:4000/api/settings/global/weekdays/0

### Change one global weekday for rooms
PUT http://localhost:4000/api/settings/global/weekdays/0
Content-Type: application/json

{
    "availability": false,
    "time_begin": "10:00",
    "time_end": "11:00"
}