### Get all notifications
GET http://localhost:3001/api/notifications

### Add new notification
POST http://localhost:3001/api/notifications
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXI1QGdtYWlsLmNvbSIsImlkIjoxLCJpYXQiOjE3MjA3NzU5MjcsImV4cCI6MTcyMDc3OTUyN30.gmz-0N4wzkGNQVem4ZRVL4ubPy6GQDLEEz-Hy_Zc4Xs

{
    "content": "First notification"
}

### Change content of desired notification
PUT http://localhost:3001/api/notifications/2
Content-Type: application/json

{
    "content": "Changed notification"
}

### Delete desired notification
DELETE http://localhost:3001/api/notifications/1