### Sign in admin
POST http://localhost:4000/api/signin
Content-Type: application/json

{
    "username": "admin@admin.com",
    "password": "pd$rCh8,"
}

### Get all rooms
GET http://localhost:4000/api/rooms
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluQGFkbWluLmNvbSIsImlkIjoxLCJpYXQiOjE3MjMxMTUzMzMsImV4cCI6MTcyMzExODkzM30.8sF1DNfaZAVOg6hU7GsemxEUE4dLvMz_MWeubZcf648

### Add new room
POST http://localhost:4000/api/rooms
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluQGFkbWluLmNvbSIsImlkIjoxLCJpYXQiOjE3MjMxMTU4NzAsImV4cCI6MTcyMzExOTQ3MH0.s9ncFbECg5rVfS1HTprV1xlQSYb716_9VRcYFq-FABk

{
    "name": "Forest",
    "capacity": 10,
    "size": 50,
    "image_path": "/images/forest.jpeg"
}

### Get desired room
GET http://localhost:4000/api/rooms/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluQGFkbWluLmNvbSIsImlkIjoxLCJpYXQiOjE3MjMxMTU4NzAsImV4cCI6MTcyMzExOTQ3MH0.s9ncFbECg5rVfS1HTprV1xlQSYb716_9VRcYFq-FABk

### Delete desired room
DELETE http://localhost:4000/api/rooms/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluQGFkbWluLmNvbSIsImlkIjoxLCJpYXQiOjE3MjI4Njc0NzksImV4cCI6MTcyMjg3MTA3OX0.CVhgBCJpGj7H6jwn6d-BUZTm3bD5k_d9_0tnivRz4Sw

### Change rooms characteristics
PUT http://localhost:4000/api/rooms/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluQGFkbWluLmNvbSIsImlkIjoxLCJpYXQiOjE3MjMxMjQ0MzksImV4cCI6MTcyMzEyODAzOX0.1apaQs0stXLaFdlixDN5E3uZ5PpDzm6C_mxGPfm0KUI

{
  "enabled": false
}