### Sign in admin
POST http://localhost:4000/api/signin
Content-Type: application/json

{
    "username": "admin@admin.com",
    "password": "pd$rCh8,"
}

### Get all rooms
GET http://localhost:4000/api/rooms
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluQGFkbWluLmNvbSIsImlkIjoxLCJpYXQiOjE3MjQyMjc4NzYsImV4cCI6MTcyNDIzMTQ3Nn0.853-C9sJekM_6tPrKjolUKz1y6kp--_3h7-fGpiPuHk

### Add new room
POST http://localhost:4000/api/rooms
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluQGFkbWluLmNvbSIsImlkIjoxLCJpYXQiOjE3MjQyMjc4NzYsImV4cCI6MTcyNDIzMTQ3Nn0.853-C9sJekM_6tPrKjolUKz1y6kp--_3h7-fGpiPuHk

{
    "name": "air",
    "capacity": 10,
    "size": 50,
    "image_path": "/images/air.jpeg"
}

### Add new date for one room
POST http://localhost:4000/api/rooms/1/settings/dates
Content-Type: application/json

{
    "date": "2024-01-02",
    "name": "New Year's Day",
    "availability": false,
    "time_begin": "10:00",
    "time_end": "11:00"
}

### Get all dates for all rooms
GET http://localhost:4000/api/rooms/settings/dates

### Get all dates for desired room
GET http://localhost:4000/api/rooms/1/settings/dates

### Delete desired date for desired room
DELETE http://localhost:4000/api/rooms/1/settings/dates/2024-08-22

### Delete all dates for desired room
DELETE http://localhost:4000/api/rooms/2/settings/dates

### Delete all dates for all rooms
DELETE http://localhost:4000/api/rooms/settings/dates

### Get desired room for desired day
GET http://localhost:4000/api/rooms/1/2024-08-22
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluQGFkbWluLmNvbSIsImlkIjoxLCJpYXQiOjE3MjQyMjc4NzYsImV4cCI6MTcyNDIzMTQ3Nn0.853-C9sJekM_6tPrKjolUKz1y6kp--_3h7-fGpiPuHk

### Delete desired room
DELETE http://localhost:4000/api/rooms/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluQGFkbWluLmNvbSIsImlkIjoxLCJpYXQiOjE3MjM4MTA0MTgsImV4cCI6MTcyMzgxNDAxOH0.HH3xOpXXXkePd7LgEkSDAhBDN2S2PlhzLIearIJqc7s

### Change rooms characteristics
PUT http://localhost:4000/api/rooms/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluQGFkbWluLmNvbSIsImlkIjoxLCJpYXQiOjE3MjMxMjQ0MzksImV4cCI6MTcyMzEyODAzOX0.1apaQs0stXLaFdlixDN5E3uZ5PpDzm6C_mxGPfm0KUI

{
  "enabled": false
}