### Get all users
GET http://localhost:3001/api/users

### Get desired user
GET http://localhost:3001/api/users/1

### Change username, name for desired user
PUT http://localhost:3001/api/users/1
Content-Type: application/json

{
    "enabled": true
}

### Delete desired user
DELETE http://localhost:3001/api/users/1