### Get all users
GET http://localhost:4000/api/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluQGFkbWluLmNvbSIsImlkIjoxLCJpYXQiOjE3MjI4NjExMDQsImV4cCI6MTcyMjg2NDcwNH0.PZFeIIxOgccUhehVy5tWHDRXSdxLzKUT57-HZr_jFks

### Get desired user
GET http://localhost:4000/api/users/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluQGFkbWluLmNvbSIsImlkIjoxLCJpYXQiOjE3MjI4NjExMDQsImV4cCI6MTcyMjg2NDcwNH0.PZFeIIxOgccUhehVy5tWHDRXSdxLzKUT57-HZr_jFks

### Change username, name for desired user
PUT http://localhost:4000/api/users/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXIyQGdtYWlsLmNvbSIsImlkIjoyLCJpYXQiOjE3MjEwNTI1ODUsImV4cCI6MTcyMTA1NjE4NX0.s4H_xOABGUaH0F1OqASEe5wg6zJt85f1AFGNklL_LCw

{
    "admin": true
}

### Delete desired user
DELETE http://localhost:4000/api/users/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXIyQGdtYWlsLmNvbSIsImlkIjoyLCJpYXQiOjE3MjEwNTI1ODUsImV4cCI6MTcyMTA1NjE4NX0.s4H_xOABGUaH0F1OqASEe5wg6zJt85f1AFGNklL_LCw