name: Deploy Backend

on:
  push:
    branches:
      - master
    paths:
      - 'backend/**' # Trigger only on changes within the backend directory

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.10.0'
          cache: 'npm'
          cache-dependency-path: backend/package-lock.json

      - name: Install dependencies
        working-directory: ./backend
        run: npm ci
      
      - name: Deploy to Render.com
        env:
          RENDER_DEPLOY_BACKEND_HOOK_URL: ${{ secrets.RENDER_DEPLOY_BACKEND_HOOK_URL }}
        run: curl -X "$RENDER_DEPLOY_BACKEND_HOOK_URL"