name: Deploy Backend

on:
  push:
    branches:
      - master
    paths:
      - 'backend/**' # Trigger only on changes within the backend directory

jobs:
  trigger-build:
    runs-on: ubuntu-latest

    steps: 
      - name: Trigger build backend to Render.com
        env:
          url: ${{ secrets.RENDER_DEPLOY_BACKEND_HOOK_URL }}
        run: |
          curl "$url"